# Generated by Django 6.0.3 on 2026-05-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_dispositivo_push'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispositivopush',
            new_name='notificacio_usuario_fdd742_idx',
            old_name='notificacio_usuario_16e311_idx',
        ),
    ]
